const PART_RULES=[
  {test:/frame\s*base|base/i,kind:"frame-base",label:"Frame Base",color:0x5c5849},
  {test:/frame\s*gasket|cathode.*gasket/i,kind:"main-gasket",label:"Frame Gasket Cathode",color:0xf28c28},
  {test:/manifold.*gasket|gasket.*manifold/i,kind:"manifold-gasket",label:"Manifold Gasket",color:0xffa447},
  {test:/frame\s*cover|cover/i,kind:"frame-cover",label:"Frame Cover",color:0x8f1f16},
  {test:/planet\s*shaft|shaft/i,kind:"shaft",label:"Planet Shaft",color:0x87929d},
  {test:/sun\s*gear|planet\s*gear|gear/i,kind:"gear",label:"Gear",color:0x69747d},
  {test:/circlip|clip/i,kind:"circlip",label:"Circlip",color:0x4f5963},
  {test:/thust|thrust.*washer|washer/i,kind:"washer",label:"Thrust Washer",color:0xbcc4cb},
  {test:/carrier/i,kind:"carrier",label:"Carrier",color:0x59616b}
];
const NUMBER_WORDS={one:1,two:2,three:3,four:4,five:5,six:6,eight:8,nine:9,ten:10};
export function classifyPart(name=""){return PART_RULES.find(x=>x.test(String(name)))||{kind:"generic",label:name||"Unnamed Part",color:0x667482};}
export function inferAction(text=""){const t=String(text).toLowerCase();if(/scan|qr code|qr\b/.test(t))return"SCAN";if(/barcode|bar code|placard|label|stick/.test(t))return"LABEL";if(/move|movement|next station/.test(t))return"MOVE";if(/inspect|check|verify|visual/.test(t))return"INSPECT";if(/pick|place|load|insert|press|fit|put|install|repeat/.test(t))return"PLACE";return"NOTE";}
export function extractQuantity(text=""){const t=String(text).toLowerCase();const digit=t.match(/\b(\d+)\b/);if(digit&&/part|piece|pcs|nos|same|gasket|gear|shaft|washer|circlip/.test(t))return Number(digit[1]);for(const [word,n] of Object.entries(NUMBER_WORDS))if(new RegExp("\\b"+word+"\\b").test(t))return n;return 1;}
function norm(v){return String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function tokens(v){return new Set(norm(v).split(/\s+/).filter(x=>x.length>2));}
export function textScore(a,b){const aa=norm(a),bb=norm(b);if(!aa||!bb)return 0;if(aa===bb)return 100;if(aa.includes(bb)||bb.includes(aa))return 78;const A=tokens(aa),B=tokens(bb);let hit=0;A.forEach(x=>{if(B.has(x))hit++});return hit*16;}
function inferNamesFromInstruction(instruction=""){const found=[];const push=x=>{const n=String(x||"").trim();if(n&&n.length>2&&!found.some(v=>norm(v)===norm(n)))found.push(n)};const known=["Frame Base","Frame Gasket Cathode","Manifold Gasket","Frame Cover","Planet Shaft","Sun Gear","Planet Gear","Circlip","Thrust Washer","Carrier"];known.forEach(n=>{const pattern=n.split(/\s+/).map(v=>v.replace(/[.*+?^()|[\]\\]/g,"\\$&")).join("\\s+");if(new RegExp(pattern,"i").test(instruction))push(n)});for(const m of String(instruction).matchAll(/([A-Za-z][A-Za-z ]{2,36})\s*\([^)]{2,80}\)/g)){let x=m[1].trim().replace(/^(the|a|an)$/i,"");x=x.replace(/^(pick|insert|put|press fit|finally|fit|through|in|of|the)\s+/i,"");if(x)push(x)}return found;}
function nearestStep(stepRows,index){let best=null;for(const s of stepRows)if(s.rowIndex<=index&&(!best||s.rowIndex>best.rowIndex))best=s;return best;}
function materialRows(rows,stepRows){const parts=[];for(let i=0;i<Math.min(rows.length,100);i++){const row=(rows[i]||[]).map(x=>String(x??"").trim()),low=row.map(x=>x.toLowerCase()),hasQty=low.some(x=>/^(q'?ty|qty|quantity)$/.test(x)||/q'?ty/.test(x)),hasPart=low.some(x=>/part\s*(no|number|code)|part #|part#|item\s*(no|number)/.test(x));if(!hasQty||!hasPart)continue;const pnIndex=low.findIndex(x=>/part\s*(no|number|code)|part #|part#|item\s*(no|number)/.test(x));const qtyIndex=low.findIndex(x=>/^(q'?ty|qty|quantity)$/.test(x)||/q'?ty/.test(x));const nameIndex=low.findIndex(x=>/bom #|description|part\s*name|component|material/.test(x));for(let r=i+1;r<Math.min(rows.length,i+45);r++){const rr=(rows[r]||[]).map(x=>String(x??"").trim()),joined=rr.join(" ").trim();if(!joined)continue;const pn=pnIndex>=0?(rr[pnIndex]||"").trim():"",desc=nameIndex>=0?(rr[nameIndex]||"").trim():"",q=qtyIndex>=0?parseFloat(String(rr[qtyIndex]||"").replace(/[^0-9.]/g,"")):1;if(!pn&&!desc){if(/^(extra care|jigs|fixtures|consumables|product \/ process|process characteristics|sign)/i.test(joined))break;continue}const st=nearestStep(stepRows,r);const inferred=inferNamesFromInstruction(st?.instruction||"");let name=desc;if(!name&&st){const pnNorm=norm(pn).replace(/ /g,"");name=inferred.find(n=>pnNorm&&norm(st.instruction).replace(/ /g,"").includes(pnNorm))||inferred[parts.filter(x=>x.stepNumber===st.number).length]||inferred[0]||""}parts.push({name:name||("Part "+pn),partNumber:pn,quantity:q||1,stepNumber:st?.number||0});}break;}return parts;}
export function parseWorkbook(workbook){const allSteps=[],allParts=[];for(const sheetName of workbook.SheetNames){const rows=XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{header:1,defval:""});const steps=[];for(let r=0;r<rows.length;r++){const row=rows[r]||[],a=String(row[0]??"").trim(),instruction=row.slice(1).map(x=>String(x??"").trim()).filter(x=>x.length>8).join(" — ");if(/^\d+$/.test(a)&&instruction)steps.push({number:Number(a),name:"Step "+a,instruction,rowIndex:r,sheetName});}allSteps.push(...steps);allParts.push(...materialRows(rows,steps));}const stepMap=new Map();for(const s of allSteps){const k=String(s.number)+"|"+s.instruction;if(!stepMap.has(k))stepMap.set(k,s)}const merged=new Map();for(const p of allParts){const key=norm((p.name||"")+"|"+(p.partNumber||""));const old=merged.get(key);if(old)old.quantity+=p.quantity;else merged.set(key,{...p,id:"part-"+(merged.size+1)})}const steps=[...stepMap.values()].sort((a,b)=>a.number-b.number).map(({rowIndex,...s})=>s);const projectName=workbook.SheetNames.find(n=>/station|assembly|op/i.test(n))||workbook.SheetNames[0]||"Generated assembly";return{projectName,parts:[...merged.values()],steps,references:[]};}
export function assignStepsToParts(assembly){for(const step of assembly.steps){if(!step.partId&&!step.partIds?.length){let best=null,score=0;for(const part of assembly.parts){const s=Math.max(textScore(step.name+" "+step.instruction,part.name),part.partNumber&&norm(step.instruction).includes(norm(part.partNumber))?90:0,textScore(classifyPart(part.name).label,step.instruction));if(s>score){score=s;best=part}}if(best&&score>=16)step.partId=best.id;}if(/manifold.*gasket/i.test(step.instruction))step.partIds=assembly.parts.filter(p=>/manifold.*gasket/i.test(p.name)).map(p=>p.id);if(step.partId&&!step.partIds?.length)step.partIds=[step.partId];if(!step.quantity||step.quantity===1)step.quantity=extractQuantity(step.instruction+" "+step.name);}return assembly;}
export function normalizeAssembly(raw,sourceName="Untitled assembly"){const parts=(raw.parts||[]).map((p,i)=>{const c=classifyPart(p.name||p.partName||p.kind||"");return{id:p.id||"part-"+(i+1),name:p.name||p.partName||c.label,partNumber:String(p.partNumber??p.part??""),quantity:Number(p.quantity||p.qty||1),kind:p.kind||c.kind,color:p.color||c.color,modelSource:p.modelSource||"unassigned"}});const steps=(raw.steps||[]).map((s,i)=>({id:s.id||"step-"+(i+1),number:Number(s.number||i+1),name:s.name||"Step "+(i+1),instruction:s.instruction||s.text||s.name||"",action:s.action||inferAction(s.instruction||s.text||s.name||""),partId:s.partId||null,partIds:s.partIds||[],quantity:Number(s.quantity||extractQuantity(s.instruction||"")),tool:s.tool||"",alert:s.alert||"",references:s.references||[],duration:Number(s.duration||1100)}));const refs=(raw.references||[]).map((r,i)=>({id:r.id||"ref-"+(i+1),label:r.label||r.name||("Reference "+(i+1)),src:r.src,stepNumbers:r.stepNumbers||[]}));return assignStepsToParts({version:"0.3",project:{name:raw.projectName||sourceName||"Generated assembly"},parts,references:refs,steps,review:{status:"requires-human-review",geometryPolicy:"exact-cad-when-available; photo reconstruction is approximate"}});}
export function mapComponentsToParts(components,parts){return(components||[]).map((c,i)=>{let best=null,bestScore=0;for(const p of parts){const s=Math.max(textScore(c.name,p.name),p.partNumber?textScore(c.name,p.partNumber):0);if(s>bestScore){best=p;bestScore=s}}return{componentName:c.name,componentIndex:c.index??i,partId:best&&bestScore>=16?best.id:null,score:bestScore};});}
export function buildDemo(){return normalizeAssembly({projectName:"Hydep Frame Sub-Assembly · Station-01",parts:[{id:"base",name:"Frame Base",partNumber:"S110AW-MDG-405"},{id:"gasket",name:"Frame Gasket Cathode",partNumber:"S110AW-MDG-602"},{id:"manifold-a",name:"Manifold Gasket A",partNumber:"S110AW-MDG-615"},{id:"manifold-b",name:"Manifold Gasket B",partNumber:"S110AW-MDG-615"},{id:"cover",name:"Frame Cover",partNumber:"S110AW-MDG-407"}],steps:[{number:1,name:"Pick & load Frame Base",instruction:"Pick & load Frame Base on Fixture with the help of Manipulator"},{number:2,name:"Scan QR Code",instruction:"Scan the QR Code with the help of the Hand Held Scanner"},{number:3,name:"Place Frame Gasket Cathode",instruction:"Pick the Frame Gasket Cathode from the Trolley and place it on the frame base"},{number:4,name:"Place manifold gasket",instruction:"Pick the manifold gasket from the Trolley and place it on the frame base",quantity:2},{number:5,name:"Place Frame Cover",instruction:"Pick the Frame Cover from the trolley and place it on the frame base",quantity:1},{number:6,name:"Move barcode to placard",instruction:"Remove the Bar Code from the Frame Cover and stick on the placard"},{number:7,name:"Movement to next station",instruction:"Movement to next station"}],references:[{id:"base",label:"Frame base",src:"./assets/hydep/base.svg",stepNumbers:[1]},{id:"gasket",label:"Frame gasket",src:"./assets/hydep/gasket.svg",stepNumbers:[3]},{id:"manifold",label:"Manifold gasket",src:"./assets/hydep/manifold.svg",stepNumbers:[4]},{id:"cover",label:"Frame cover",src:"./assets/hydep/cover.svg",stepNumbers:[5]},{id:"exploded",label:"Exploded reference",src:"./assets/hydep/exploded.svg",stepNumbers:[7]}]});}
